name: Link Check
on: [push, pull_request]
permissions:
  contents: read
jobs:
  linkcheck:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4.4.0
      - name: Run Lychee
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8  # v2.9.0
        with:
          args: >-
            --no-progress
            --config .lychee.toml
            .
          fail: true
